spring:
  application:
    name: chat-spring
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER_URI}
  flyway:
    out-of-order: true

server:
  port: 8100