spring:
  autoconfigure:
    exclude: org.springframework.boot.kafka.autoconfigure.KafkaAutoConfiguration
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
